# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros

In [4]:
arr = np.zeros(10)

#### Create an array of 10 ones

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [6]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [7]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [8]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [18]:
np.random.rand()

0.6787077241340527

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [19]:
np.random.rand(25)

array([0.03581808, 0.17501771, 0.65977743, 0.1481098 , 0.02666967,
       0.82569069, 0.74556445, 0.64307145, 0.62873585, 0.99883176,
       0.79299665, 0.861304  , 0.19408943, 0.15115035, 0.1633713 ,
       0.04636447, 0.20635551, 0.10753109, 0.43788684, 0.574827  ,
       0.57963816, 0.70911959, 0.89269356, 0.16892765, 0.40998365])

#### Create the following matrix:

In [33]:
np.random.normal(0,26,(5,5))


array([[ 16.30341463,  42.66683677, -31.77515071,  -9.17219561,
          5.44672042],
       [  8.09130655, -25.15931289,  -9.08891915, -28.85088647,
         45.63383388],
       [-51.16692871,  -5.78381382,  43.12885009,   9.54508449,
        -44.77486097],
       [  1.63154691,   2.02545659,   4.63491492, -27.42243221,
        -15.75898557],
       [ -3.07382427, -40.79467397, -39.28289889, -30.17569917,
         25.9211322 ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [34]:
 np.linspace(0, 1, 20)



array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

20

array([[ 2],
       [ 7],
       [12]])

array([21, 22, 23, 24, 25])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Great Job!